/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista.Empresa;

import entidad.Empresa;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import negocio.GestorPrincipal;
import vista.JfrmPortadaP;

/**
 *
 * @author Diego Iturrizaga
 */
public class JfrmRegistrarEmp extends javax.swing.JFrame {

    /**
     * Creates new form JpanRegistrarEmp
     */
    public JfrmRegistrarEmp() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Agencia de Empleos");
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.png")).getImage());
        ((JPanel)getContentPane()).setOpaque(false);
        ImageIcon uno=new ImageIcon(this.getClass().getResource("/imagenes/fondo3.jpg"));
        JLabel fondo= new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jtxfRaS = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxfRuc = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPassword1 = new javax.swing.JPasswordField();
        jLabel15 = new javax.swing.JLabel();
        jPassword2 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jtxfEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxfDireccion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxfTelefono = new javax.swing.JTextField();
        btnAceptarRE = new javax.swing.JButton();
        btnCancelarRE = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Razon Social : ");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("RUC : ");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Clave :");

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Confirmar Clave :");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("E-mail : ");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Direccion : ");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Telefono : ");

        btnAceptarRE.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAceptarRE.setText("Aceptar");
        btnAceptarRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarREActionPerformed(evt);
            }
        });

        btnCancelarRE.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCancelarRE.setText("Cancelar");
        btnCancelarRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarREActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTRA A TU EMPRESA");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/empresa3.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnAceptarRE, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(btnCancelarRE, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel15))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPassword2)
                                    .addComponent(jtxfTelefono, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxfRuc, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxfRaS, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPassword1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxfDireccion)
                                    .addComponent(jtxfEmail))))
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(53, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxfRaS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxfRuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtxfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptarRE, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarRE, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarREActionPerformed
        /*Leemos los datos del usuario*/
        Empresa empresa = new Empresa();

        empresa.setRazonSocial(jtxfRaS.getText());

        if (jPassword1.getText().length() >= 6) {

            if (jPassword1.getText().equalsIgnoreCase(jPassword2.getText())) {
                empresa.setPassword(jPassword2.getText());
            } else {
                JOptionPane.showMessageDialog(this, "Las claves no coinciden",
                    "Error", JOptionPane.ERROR_MESSAGE);
            }
            empresa.setRuc(jtxfRuc.getText());
            if (jtxfRuc.getText().length() < 11 || jtxfRuc.getText().length() > 11) {
                JOptionPane.showMessageDialog(this, " RUC incorrecto!!!", "Error", JOptionPane.ERROR_MESSAGE);
            } else {

                empresa.setEmail(jtxfEmail.getText());
                empresa.setDireccion(jtxfDireccion.getText());
                empresa.setTelefono(jtxfTelefono.getText());

                /*Validamos los datos, usamos la versión resumida del "if-else" anidado*/
                if (empresa.getRazonSocial().trim().equals("") == true) {
                    JOptionPane.showMessageDialog(this, "La razon social no puede estar vacío", "Error", JOptionPane.ERROR_MESSAGE);
                } else if (empresa.getPassword().trim().equals("") == true) {
                    JOptionPane.showMessageDialog(this, "Ingrese su clave", "Error", JOptionPane.ERROR_MESSAGE);
                } else if (empresa.getEmail().trim().equals("") == true) {
                    JOptionPane.showMessageDialog(this, "Ingrese su Email", "Error", JOptionPane.ERROR_MESSAGE);
                } else if (empresa.getDireccion().trim().equals("") == true) {
                    JOptionPane.showMessageDialog(this, "Ingrese su Direccion", "Error", JOptionPane.ERROR_MESSAGE);
                } else if (empresa.getTelefono().trim().equals("") == true) {
                    JOptionPane.showMessageDialog(this, "Ingrese su Telefono", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    /*Si pasamos todas las validaciones, lo registramos*/
                    boolean estado = GestorPrincipal.getGestorUsuarioEmpresa().registrarEmpresa(empresa);
                    if (estado == true) {
                        JOptionPane.showMessageDialog(this, "¡Usuario registrado con éxito!", "Registrado", JOptionPane.INFORMATION_MESSAGE);
                        int respuesta = JOptionPane.showConfirmDialog(this, "¿Desea guardar los cambios efectuados?", "Guardar", JOptionPane.YES_NO_OPTION);
                        if (respuesta == JOptionPane.YES_OPTION) {
                            boolean estad = GestorPrincipal.getGestorBaseDeDatos().guardarCambios();
                            JfrmPerfilEmpresa E = new JfrmPerfilEmpresa(empresa.getRuc());
                            dispose();
                        } else if (respuesta == JOptionPane.NO_OPTION) {
                            //Limpiar L = new Limpiar();

                        }
                        
                    } else {
                        JOptionPane.showMessageDialog(this, "No se pudo registrar al Usuario, verifique que no esté ya registrado.", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "La contraseña debe tener 6 a mas digitos",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAceptarREActionPerformed

    private void btnCancelarREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarREActionPerformed
        JfrmPortadaP P= new JfrmPortadaP();
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnCancelarREActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarRE;
    private javax.swing.JButton btnCancelarRE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jPassword1;
    private javax.swing.JPasswordField jPassword2;
    private javax.swing.JTextField jtxfDireccion;
    private javax.swing.JTextField jtxfEmail;
    private javax.swing.JTextField jtxfRaS;
    private javax.swing.JTextField jtxfRuc;
    private javax.swing.JTextField jtxfTelefono;
    // End of variables declaration//GEN-END:variables
}
