/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista;

import entidad.Anuncio;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import negocio.GestorPrincipal;


/**
 *
 * @author Diego Iturrizaga
 */
public class JfrmPortadaP extends javax.swing.JFrame {
    String area,puesto,ubicacion;

    /**
     * Creates new form JfrmPortadaP
     */
    public JfrmPortadaP() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Agencia de Empleos");
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.png")).getImage());
        ((JPanel)getContentPane()).setOpaque(false);
        ImageIcon uno=new ImageIcon(this.getClass().getResource("/imagenes/fondo3.jpg"));
        JLabel fondo= new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());
        iniciarComponentes();
    }
                
     public void iniciarComponentes(){   
        setLocationRelativeTo(null);
        setResizable(false);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscarPP = new javax.swing.JButton();
        btnrRegistrar = new javax.swing.JButton();
        btnIniciarSesion = new javax.swing.JButton();
        jboxUbicacion = new javax.swing.JComboBox();
        jboxPuesto = new javax.swing.JComboBox();
        jboxArea = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(685, 620));

        btnBuscarPP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBuscarPP.setText("Buscar");
        btnBuscarPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPPActionPerformed(evt);
            }
        });

        btnrRegistrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnrRegistrar.setText("Registrarse");
        btnrRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrRegistrarActionPerformed(evt);
            }
        });

        btnIniciarSesion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnIniciarSesion.setText("Iniciar Sesion");
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });

        jboxUbicacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jboxUbicacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Ubicacion", "Ate", "Barranco", "Bellavista", "Breña", "Callao", "Carmen de la Legua", "Cercado de Lima", "Chorrillos", "Comas", "El Agustino", "Independencia", "Jesús María", "La Molina", "La Perla", "La Punta", "La Victoria", "Lince", "Los Olivos", "Magdalena del Mar", "Miraflores", "Pueblo Libre", "Puente Piedra", "Rimac", "San Borja", "San Isidro", "San Juan de Lurigancho", "San Juan de Miraflores", "San Luis", "San Martin de Porres", "San Miguel", "Santa Anita", "Santa Rosa", "Santiago de Surco", "Surquillo", "Ventanilla", "Villa El Savador", "Villa María del Triunfo" }));
        jboxUbicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jboxUbicacionActionPerformed(evt);
            }
        });

        jboxPuesto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jboxPuesto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Cargo", "Analista/Asistente", "Ejecutivo Comercial", "Gerencia", "Jefe / Supervisor", "Practicante", "Tecnicos Operativos", "Formador", "Vendedor", "Otros" }));
        jboxPuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jboxPuestoActionPerformed(evt);
            }
        });

        jboxArea.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jboxArea.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione un Rubro", "Administracion/Servicios Generales", "Auditoria", "Banca", "Comercial", "Comercio Exterior/Aduanas", "Compras/Logistica", "Consultoria", "Contabilidad", "Finanzas", "Hoteleria/Turismo/Restaurantes", "Ingenieria", "Investigacion y Desarrollo", "Legal", "Marketing/Publicidad", "Medios Digitales / Internet", "Recursos Humanos", "Seguridad Salud Ocupacional y Medio Ambiente", "Sistemas", "Ventas", "Otros" }));
        jboxArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jboxAreaActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Empresa", "Rubro", "Cargo", "Pagina Web", "Descripcion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jboxArea, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(jboxPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jboxUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarPP, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(btnrRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnIniciarSesion)
                        .addGap(33, 33, 33)
                        .addComponent(btnrRegistrar)
                        .addGap(54, 54, 54))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarPP)
                    .addComponent(jboxUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jboxPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jboxArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPPActionPerformed
        ArrayList<Anuncio> A = GestorPrincipal.getGestorUsuarioPersona().buscarTrabajo(jboxArea.getSelectedItem().toString(), 
                jboxPuesto.getSelectedItem().toString(), jboxUbicacion.getSelectedItem().toString());        
        //<Empresa> E = GestorPrincipal.getGestorBaseDeDatos().
        
                
        try{
        if(A.isEmpty()){
            JOptionPane.showMessageDialog(this, "Aún no hay Anuncios registrados.", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            Anuncio anuncio;
            for(int i=0; i<A.size(); i++){
                anuncio = A.get(i);
                jTable1.getModel().setValueAt(anuncio.getEmpresa().getRazonSocial(), i, 0);
                jTable1.getModel().setValueAt(anuncio.getRubro(), i, 1);
                jTable1.getModel().setValueAt(anuncio.getCargo(), i, 2);
                jTable1.getModel().setValueAt(anuncio.getPagWeb(), i, 3);
                jTable1.getModel().setValueAt(anuncio.getDescripcion(), i, 4);
            }
        }
        }catch(Exception E){
            
        }
    }//GEN-LAST:event_btnBuscarPPActionPerformed

    private void btnrRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrRegistrarActionPerformed
        JfrmOpciones jfrmopciones= new JfrmOpciones();
        setVisible(false);
    }//GEN-LAST:event_btnrRegistrarActionPerformed

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        JfrmInicioDeSesion jfrmInicioDeSesion = new JfrmInicioDeSesion();
        setVisible(false);
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void jboxUbicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jboxUbicacionActionPerformed
        ubicacion=jboxArea.getSelectedItem().toString(); // TODO add your handling code here:
    }//GEN-LAST:event_jboxUbicacionActionPerformed

    private void jboxPuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jboxPuestoActionPerformed
        puesto=jboxArea.getSelectedItem().toString();// TODO add your handling code here:
    }//GEN-LAST:event_jboxPuestoActionPerformed

    private void jboxAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jboxAreaActionPerformed
        area=jboxArea.getSelectedItem().toString();

    }//GEN-LAST:event_jboxAreaActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        ArrayList<Anuncio> A = GestorPrincipal.getGestorUsuarioPersona().buscarTrabajo(jboxArea.getSelectedItem().toString(), jboxPuesto.getSelectedItem().toString(), jboxUbicacion.getSelectedItem().toString());
                
        int fila = jTable1.rowAtPoint(evt.getPoint());
        int colum = jTable1.columnAtPoint(evt.getPoint());
        
        if(fila>=0 && colum==3 && jTable1.isEnabled()){
            System.out.println(fila);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarPP;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnrRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox jboxArea;
    private javax.swing.JComboBox jboxPuesto;
    private javax.swing.JComboBox jboxUbicacion;
    // End of variables declaration//GEN-END:variables
}
